### ISSUE TITLE
什么时候出vue mobile

### ISSUE THREAD

**Issue by seulfish** [arco-design/arco-design-vue#3247] opened 2024-07-25 10:45 UTC
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
什么时候出vue mobile

## What problem does this feature solve?
什么时候出vue mobile

**Comment by geelato** [comment] 2024-07-30 14:33
期待

**Comment by oljc** [comment] 2024-09-09 06:29
暂时没有 Vue 版计划，Duplicate of #1573

**Closed by oljc** 2024-09-09 06:29 UTC
