### ISSUE TITLE
color-picker缺少样式文件index.css

### ISSUE THREAD

**Issue by LvHuaiSheng** [arco-design/arco-design-vue#3051] opened 2024-03-30 02:35 UTC
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Browser:** firefox123.0
- **Framework version:** vue 3
- **Package Name And Version:** @arco-design/web-vue@2.55.1

## Steps to reproduce
引入color-picker组件即可复现

## What is expected?
已经从2.55.0等到了2.55.1问题依旧存在

到npmjs中插件打包完成的代码发现也是缺少文件，如下图：
![微信截图_20240330103158](https://github.com/arco-design/arco-design-vue/assets/35132878/5ff1ede1-92f4-4fe3-bbbf-81b64f3a7ab6)
![微信截图_20240330103207](https://github.com/arco-design/arco-design-vue/assets/35132878/a9eaa104-2ab2-4194-8e04-6bc33ea07e82)

**Comment by LvHuaiSheng** [comment] 2024-03-30 09:20
临时解决：手动创建`index.css`文件并放入到`node_modules\@arco-design\web-vue\es\color-picker\style`下，index.css内容见附件
[index.txt](https://github.com/arco-design/arco-design-vue/files/14811352/index.txt)

**Comment by LIjiAngChen8** [comment] 2024-03-30 10:13
Duplicate of #3025

**Closed by LIjiAngChen8** 2024-03-30 10:13 UTC
