### ISSUE TITLE
级联选择器功能出一个选择即改变的吧 changeOnSelect 这个属性

### ISSUE THREAD

**Issue by wangmou12138** [arco-design/arco-design-vue#3401] opened 2024-12-30 01:28 UTC
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.56.3
- **Browser:** chrome131.0.0.0

## What is expected?
级联选择器功能出一个选择即改变的吧 changeOnSelect 这个属性

**Comment by oljc** [comment] 2024-12-30 01:29
Duplicate of #3395

**Closed** 2024-12-30 01:29 UTC
Labels: 🔄 Duplicate
