### ISSUE TITLE
[Table] Table 组件 select-all 和 selection-change 事件，期望把选中的 records 都传过来

### ISSUE THREAD

**Issue by rudderstock** [arco-design/arco-design-vue#2508] opened 2023-06-20 03:06 UTC
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
arco-design-react 相关事件都是有传 selectedRows，期望能保持一致
![image](https://github.com/arco-design/arco-design-vue/assets/28646002/62945d12-6d84-4c2b-b42b-5dcca852f76a)

## What problem does this feature solve?
选中的数据不仅仅需要id，也需要选中数据中的其他数据

**Comment by caprimoon** [comment] 2023-09-07 01:06
@flsion 大佬 苦这个久矣，望优先解决这个，很多场景需要用到。不说其他UI库，同是acro的react版都有🤦‍♂️🤦‍♂️

**Comment by kanhebei** [comment] 2023-09-12 14:29
@flsion 大佬 苦这个久矣，望优先解决这个，很多场景需要用到。

**Comment by dddddd1** [comment] 2024-04-19 05:45
大家怎么解决的呢

**Comment by oljc** [comment] 2024-05-07 07:46
Duplicate of #2288

**Closed by oljc** 2024-05-07 07:46 UTC
