### ISSUE TITLE
table开启虚拟列表后，不显示空数据状态

### ISSUE THREAD

**Issue by classfang** [arco-design/arco-design-vue#2400] opened 2023-05-09 07:26 UTC
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.45.3
- **Browser:** chrome112.0.0.0

**Comment by LIjiAngChen8** [comment] 2024-01-25 08:22
Duplicate of #2946 

> [!TIP]
> 重复 issue 关闭，后者包含更详细的描述。请移步至相关 issue 进行进一步讨论和跟踪。

**Closed by LIjiAngChen8** 2024-01-25 08:22 UTC
