### ISSUE TITLE
color-picker 打包时提示缺少 @input-size-mini-height 

### ISSUE THREAD

**Issue by m15538691216** [arco-design/arco-design-vue#3064] opened 2024-04-07 09:58 UTC
![1712483887548](https://github.com/arco-design/arco-design-vue/assets/58064602/d749336b-2133-4c2d-b7ef-76c06b622bd9)
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.55.0
- **浏览器版本:** chrome123.0.0.0

**Comment by LIjiAngChen8** [comment] 2024-04-08 07:31
Duplicate of #3025

**Closed by LIjiAngChen8** 2024-04-08 07:31 UTC
Labels: type: 🐞 bug
